# Generated by Django 5.1.2 on 2024-10-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('rent_vehicle', 'Can rent vehicle'), ('return_vehicle', 'Can return vehicle'), ('report_defective_vehicle', 'Can report defective vehicle'), ('pay_charges', 'Can pay charges'), ('track_vehicle', 'Can track vehicle'), ('charge_vehicle', 'Can charge vehicle'), ('repair_vehicle', 'Can repair vehicle'), ('move_vehicle', 'Can move vehicle'), ('generate_reports', 'Can generate reports')]},
        ),
    ]
