# Generated by Django 5.1.2 on 2024-11-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customerprofile_charges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('rent_vehicle', 'Can rent vehicle'), ('return_vehicle', 'Can return vehicle'), ('report_defective_vehicle', 'Can report defective vehicle'), ('pay_charges', 'Can pay charges'), ('request_discount', 'Can request discounts'), ('track_vehicle', 'Can track vehicle'), ('charge_vehicle', 'Can charge vehicle'), ('repair_vehicle', 'Can repair vehicle'), ('move_vehicle', 'Can move vehicle'), ('verify_requests', 'Can verify request'), ('generate_reports', 'Can generate reports')]},
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
