# Generated by Django 5.1.2 on 2024-11-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_partnerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerProfile',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('rent_vehicle', 'Can rent vehicle'), ('return_vehicle', 'Can return vehicle'), ('report_defective_vehicle', 'Can report defective vehicle'), ('pay_charges', 'Can pay charges'), ('track_vehicle', 'Can track vehicle'), ('charge_vehicle', 'Can charge vehicle'), ('repair_vehicle', 'Can repair vehicle'), ('move_vehicle', 'Can move vehicle'), ('generate_reports', 'Can generate reports'), ('add_partners', 'Can add partners'), ('request_discount', 'Can request discounts'), ('verify_requests', 'Can verify request')]},
        ),
    ]
