# Generated by Django 5.1.2 on 2024-11-01 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='location',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='station_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehicles.stationlocation'),
            preserve_default=False,
        ),
    ]
