# Generated by Django 5.1.2 on 2024-11-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_location_vehicle_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals_end', to='vehicles.stationlocation'),
        ),
    ]
