# Generated by Django 5.1.2 on 2024-11-01 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_rental_end_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='action_taken',
            field=models.CharField(choices=[('Charged', 'Charged'), ('Repaired', 'Repaired'), ('Relocated', 'Relocated'), ('ReportReceived', 'ReportReceived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_maintenance_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
