# Generated by Django 5.1.2 on 2024-11-01 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_repairslog_action_taken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('charge_up_to', models.IntegerField()),
                ('original_battery_level', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
