# Generated by Django 5.1.2 on 2024-11-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_chargeslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.stationlocation'),
        ),
    ]
