# Generated by Django 5.1.2 on 2024-11-05 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_discountrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrequests',
            name='id_valid_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 30, 0, 0)),
            preserve_default=False,
        ),
    ]
