# Generated by Django 5.1.2 on 2024-11-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_partner_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_use',
            field=models.IntegerField(default=1),
        ),
    ]
