# Generated by Django 5.1.2 on 2024-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_remove_coupon_used_by_couponuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreporteddefects',
            name='defect_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
