# Generated by Django 5.1.2 on 2024-11-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_customerreporteddefects_defect_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.stationlocation'),
        ),
    ]
