# Generated by Django 5.1.2 on 2024-11-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_vehicle_station_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
